### ISSUE TITLE
npm package

### ISSUE THREAD

**Issue by jdnichollsc** [KilledByAPixel/ZzFX#3]
Hello mate,

What do you think about distributing this awesome tool as a npm package?

Thanks for your help!

**Comment by KilledByAPixel** [comment]
yes, i will try to do that soon!

**Comment by jdnichollsc** [comment]
I created this PR to add **ZzFX** from cdnjs :) https://github.com/cdnjs/packages/pull/484

**Comment by KilledByAPixel** [comment]
zzfx is published to npm!

this is my first npm package so let me know if it is working ok.
