### ISSUE TITLE
Sort parameters by estimated frequency

### ISSUE THREAD

**Issue by joseprio** [KilledByAPixel/ZzFX#4]
I noticed that in the sounds I used for my game there were a number of parameters that are generally undefined, like randomness, pitchJumpTime, repeatTime... however the last two, tremolo and decay are always used, so it's not possible shorten the arrays to take advantage of the defaults.

Perhaps it would be useful to tweak the parameter order for some byte size gains?

**Comment by joseprio** [comment]
After thinking about it, to me it made sense to have this kind of optimisation done in a separate step, so I created a script: https://github.com/joseprio/zzfx-minifier .

It performs the following optimisations:
- If a parameter is unused, it will be defined as a constant inside the `ZzFX` function
- If all `ZzFX` sounds use certain argument, the default value will be removed
- Determines what is the most commonly used value for an argument, and used that as the default
- Reorders the arguments in descending frequency of use

I'm sure that smarter methods would provide slightly better results. In my current use case, it made the ZIP file 17 bytes smaller.

**Comment by KilledByAPixel** [comment]
Thank you for looking into this, your solution is interesting. I tried to set up the parameters so they are somewhat in order of frequency of use, but it's hard to predict, and varies a lot for what type of sound effect.
