### ISSUE TITLE
Custom modulation function

### ISSUE THREAD

**Issue by dy** [KilledByAPixel/ZzFX#9]
Right now half-cosine is used for modulation, eg.
```
zzfx.play(...[,0,1925,,2.4,0,,,,,,,,,2,,,.5])
```
produces the following spectrogram:
![image](https://user-images.githubusercontent.com/300067/128363722-8440a32f-bf06-4fef-b0d5-bb898cb31541.png)

Would be nice to have another modulation types, eg. sin:
![image](https://user-images.githubusercontent.com/300067/128364690-92c66cef-45a3-4f7b-996f-4e94b5ad8514.png)
saw:
![image](https://user-images.githubusercontent.com/300067/128364939-8e999b90-7942-4538-9a86-c5bcbb62d3bc.png)
tri:
![image](https://user-images.githubusercontent.com/300067/128365155-b0380487-75ff-486d-9eaa-034f5d3431ba.png)

**Comment by dy** [comment]
although the difference is not so much noticeable.
Maybe that needs somewhat generic approach instead. Any param can actually be a curve, not static value.
Erlang has nice notion of atoms/tuples, passing them instead of static values would allow for really expressive description:
```
zzfx.play(...[,0,{linear, 2, 4},,2.4,0,,,,,,,,,{sin, 1, 3},,,.5])
```
That brings to an idea that some params, like `slide` etc could be replaced with such "tokens".

**Comment by KilledByAPixel** [comment]
Nice spectograms! It uses cosine for the modulation, not half cosine, what makes you think that? 

The reason I chose cosine over sine is that for slow modulations the cosine is 1 at 0 so the sound will begin at its given frequency rather then ramping in from 0.

You are right though, it would be cool to have more options for this!

**Comment by dy** [comment]
For spectrograms I used [webaudio-viz](https://github.com/fenomas/webaudio-viz)

**Comment by dy** [comment]
> It uses cosine for the modulation, not half cosine, what makes you think that?
Right, to goes below 0, so `f` turns to negative, I missed it, thought it does `Math.abs` somewhere.
